vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    images:
      uri_prefix: /media/images/
      upload_destination: "%kernel.project_dir%/public/media/images/"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
